apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: i0iwey0te-nodejs-prod
  namespace: rhtap-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/i0iwey0te-nodejs/overlays/prod
    repoURL: https://github.com/rhtap-rhdh-qe/i0iwey0te-nodejs-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
