apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i0iwey0te-nodejs
  janus-idp.io/tekton: i0iwey0te-nodejs
  backstage.io/kubernetes-id: i0iwey0te-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i0iwey0te-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
